"""Deterministically lower Fixture IR into marker-free backend seed sources."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class FixtureLoweringResult:
    sources: dict[str, str] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors


class FixtureLowerer:
    def lower(
        self,
        fixture_ir: dict[str, Any],
        database_manifest: dict[str, Any],
    ) -> FixtureLoweringResult:
        errors: list[str] = []
        table_entities = {
            str(row.get("entity", ""))
            for row in database_manifest.get("tables", [])
            if isinstance(row, dict) and str(row.get("entity", ""))
        }
        sets = [
            row for row in fixture_ir.get("fixture_sets", []) if isinstance(row, dict)
        ]
        for fixture_set in sets:
            for row in fixture_set.get("rows", []):
                entity = str(row.get("entity_key", "")) if isinstance(row, dict) else ""
                if entity not in table_entities:
                    errors.append(f"ARC3410 FIXTURE_ENTITY_UNPLANNED: {entity!r}.")
        if errors:
            return FixtureLoweringResult(errors=list(dict.fromkeys(errors)))

        sources: dict[str, str] = {}
        imports: list[tuple[str, str]] = []
        sets_by_requirement: dict[str, list[dict[str, Any]]] = {}
        for fixture_set in sets:
            sets_by_requirement.setdefault(
                str(fixture_set.get("requirement_id", "")), []
            ).append(fixture_set)
        for requirement_id, requirement_sets in sorted(sets_by_requirement.items()):
            path = f"backend/src/fixtures/{_path_token(requirement_id)}.ts"
            symbol = f"fixtureSets_{_identifier_token(requirement_id)}"
            sources[path] = (
                "// Generated by ARC. Do not edit.\n"
                f"export const {symbol} = "
                f"{json.dumps(requirement_sets, ensure_ascii=False, indent=2)} as const;\n"
            )
            imports.append((symbol, f"./{_path_token(requirement_id)}.js"))

        sources["backend/src/fixtures/index.ts"] = _render_index(
            imports,
            database_manifest,
        )
        return FixtureLoweringResult(sources=sources)


def fixture_source_paths(fixture_ir: dict[str, Any]) -> list[str]:
    paths = ["backend/src/fixtures/index.ts"]
    paths.extend(
        f"backend/src/fixtures/{_path_token(str(row.get('requirement_id', '')))}.ts"
        for row in fixture_ir.get("fixture_sets", [])
        if isinstance(row, dict)
    )
    return sorted(set(paths))


def _render_index(
    imports: list[tuple[str, str]],
    database_manifest: dict[str, Any],
) -> str:
    tables = sorted(
        str(row.get("entity", ""))
        for row in database_manifest.get("tables", [])
        if isinstance(row, dict) and str(row.get("entity", ""))
    )
    lines = [
        "// Generated by ARC. Do not edit.",
        'import { sqliteDatabase } from "../db/client.js";',
        *[f'import {{ {symbol} }} from {json.dumps(specifier)};' for symbol, specifier in imports],
        "",
        "type FixtureValue = string | number | boolean | null | Readonly<Record<string, unknown>>;",
        "interface FixtureRow {",
        "  entity_key: string;",
        "  values: Readonly<Record<string, FixtureValue>>;",
        "}",
        "interface FixtureSet {",
        "  requirement_id: string;",
        "  rows: readonly FixtureRow[];",
        "}",
        "",
        "const fixtureSets: readonly FixtureSet[] = [",
        *[f"  ...{symbol}," for symbol, _ in imports],
        "] as const;",
        "",
        "const seed = sqliteDatabase.transaction((requirementId: string) => {",
        *[f"    sqliteDatabase.exec({json.dumps(f'DELETE FROM {_quote_identifier(table)}')});" for table in reversed(tables)],
        "    for (const fixtureSet of fixtureSets) {",
        "      if (fixtureSet.requirement_id !== requirementId) continue;",
        "      for (const row of fixtureSet.rows) {",
        "        const entries = Object.entries(row.values).map(([field, value]) => [",
        "          field,",
        "          typeof value === \"boolean\" ? Number(value) :",
        "            value !== null && typeof value === \"object\" ? JSON.stringify(value) : value,",
        "        ] as const);",
        '        const columns = entries.map(([field]) => `"${field.replaceAll(\'"\', \'""\')}"`).join(", ");',
        '        const placeholders = entries.map(() => "?").join(", ");',
        '        const table = `"${row.entity_key.replaceAll(\'"\', \'""\')}"`;',
        "        sqliteDatabase.prepare(`INSERT INTO ${table} (${columns}) VALUES (${placeholders})`).run(",
        "          ...entries.map(([, value]) => value),",
        "        );",
        "      }",
        "    }",
        "});",
        "",
        "export function seedFor(requirementId: string): void {",
        '  sqliteDatabase.pragma("foreign_keys = OFF");',
        "  try {",
        "    seed(requirementId);",
        "  } finally {",
        '    sqliteDatabase.pragma("foreign_keys = ON");',
        "  }",
        "}",
        "",
    ]
    return "\n".join(lines)


def _quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _path_token(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "requirement"


def _identifier_token(value: str) -> str:
    token = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_")
    if not token or token[0].isdigit():
        token = f"requirement_{token}"
    return token
