from __future__ import annotations

import copy
import json
import posixpath
import re
from dataclasses import dataclass, field
from typing import Any


TYPE_MANIFEST_SCHEMA_VERSION = 1
DATABASE_MANIFEST_SCHEMA_VERSION = 2
TYPES_GENERATED = "TYPES_GENERATED"
DATABASE_SCHEMA_LOWERED = "DATABASE_SCHEMA_LOWERED"

DESIGN_TYPE_MAP = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "date": "string",
    "datetime": "string",
    "uuid": "string",
    "json": "JsonValue",
}

DATABASE_TYPE_MAP = {
    **DESIGN_TYPE_MAP,
    "foreign_key": "string",
}


@dataclass(slots=True)
class TypeLoweringResult:
    manifest: dict[str, Any]
    sources: dict[str, str] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors


@dataclass(slots=True)
class DatabaseSchemaLoweringResult:
    manifest: dict[str, Any]
    sources: dict[str, str] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors


class TypeLowerer:
    """Render the complete canonical TypeScript type world from frozen registries."""

    def lower(
        self,
        symbol_registry: dict[str, Any],
        file_registry: dict[str, Any],
    ) -> TypeLoweringResult:
        errors: list[str] = []
        symbols = _index_symbols(symbol_registry, errors, "ARC3301")
        locations = _index_symbol_locations(file_registry, errors, "ARC3302")
        _validate_registry_statuses(symbol_registry, file_registry, errors, "ARC3303")
        _validate_required_files(
            file_registry,
            {
                "shared/src/contracts/runtime.ts",
                "shared/src/contracts/index.ts",
                "shared/src/index.ts",
            },
            errors,
            "ARC3302",
        )
        definitions: list[dict[str, Any]] = []
        sources: dict[str, str] = {}

        if not errors:
            contract_files: dict[str, list[dict[str, Any]]] = {}
            entity_files: dict[str, list[dict[str, Any]]] = {}
            for symbol_id, symbol in sorted(symbols.items()):
                location = locations.get(symbol_id)
                if location is None:
                    errors.append(f"ARC3304 TYPE_LOCATION_MISSING: no file for {symbol_id}.")
                    continue
                path = str(location["path"])
                kind = str(symbol.get("kind", ""))
                if kind == "DATA_CONTRACT":
                    if not path.startswith("shared/src/contracts/"):
                        errors.append(
                            f"ARC3304 TYPE_LOCATION_MISSING: contract {symbol_id} is outside shared contracts."
                        )
                        continue
                    contract_files.setdefault(path, []).append(symbol)
                elif kind == "ENTITY_TYPE":
                    if not path.startswith("backend/src/db/schema/"):
                        errors.append(
                            f"ARC3304 TYPE_LOCATION_MISSING: entity {symbol_id} is outside database schema."
                        )
                        continue
                    entity_files.setdefault(path, []).append(symbol)

            for path, rows in sorted(contract_files.items()):
                sources[path] = _render_contract_file(rows, errors)
                definitions.extend(_definition_rows(rows, path, "DATA_CONTRACT"))
            for path, rows in sorted(entity_files.items()):
                if len(rows) != 1:
                    errors.append(
                        f"ARC3305 ENTITY_TYPE_INVALID: expected one entity type in {path}, found {len(rows)}."
                    )
                    continue
                sources[path] = _render_entity_type_file(rows[0], errors)
                definitions.extend(_definition_rows(rows, path, "ENTITY_TYPE"))

            runtime_path = "shared/src/contracts/runtime.ts"
            sources[runtime_path] = _render_runtime_types()
            contract_paths = sorted(contract_files)
            sources["shared/src/contracts/index.ts"] = _render_barrel(
                "shared/src/contracts/index.ts",
                [runtime_path, *contract_paths],
            )
            sources["shared/src/index.ts"] = (
                "// Generated by ARC. Do not edit.\n"
                'export * from "./contracts/index.js";\n'
            )
            definitions.append(
                {
                    "symbol_id": "SYSTEM.JsonValue",
                    "symbol": "JsonValue",
                    "kind": "RUNTIME_TYPE",
                    "path": runtime_path,
                }
            )

        manifest = {
            "schema_version": TYPE_MANIFEST_SCHEMA_VERSION,
            "status": TYPES_GENERATED if not errors else "TYPE_LOWERING_FAILED",
            "definitions": sorted(definitions, key=lambda item: item["symbol_id"]),
            "planned_files": sorted(sources),
            "generated_files": [] if errors else sorted(sources),
        }
        return TypeLoweringResult(
            manifest=manifest,
            sources={} if errors else sources,
            errors=list(dict.fromkeys(errors)),
        )


class DatabaseSchemaLowerer:
    """Lower logical Schema IR into deterministic SQLite + Drizzle source files."""

    def lower(
        self,
        database_schema: dict[str, Any],
        symbol_registry: dict[str, Any],
        file_registry: dict[str, Any],
    ) -> DatabaseSchemaLoweringResult:
        errors: list[str] = []
        warnings: list[str] = []
        symbols = _index_symbols(symbol_registry, errors, "ARC3401")
        locations = _index_symbol_locations(file_registry, errors, "ARC3402")
        _validate_registry_statuses(symbol_registry, file_registry, errors, "ARC3403")
        _validate_required_files(
            file_registry,
            {"backend/src/db/schema/index.ts"},
            errors,
            "ARC3402",
        )
        entities = _index_entities(database_schema, errors)
        entity_symbols = _index_entity_symbols(symbols, errors)
        _validate_database_status(database_schema, errors)

        sources: dict[str, str] = {}
        tables: list[dict[str, Any]] = []
        application_constraints = _application_constraints(database_schema)

        if not errors:
            _validate_entity_coverage(entities, entity_symbols, errors)

        if not errors:
            for entity_key, entity in sorted(entities.items()):
                type_symbol, table_symbol = entity_symbols[entity_key]
                if type_symbol.get("fields") != entity.get("fields"):
                    errors.append(
                        f"ARC3407 ENTITY_SYMBOL_INVALID: frozen fields differ for {entity_key}."
                    )
                    continue
                type_location = locations.get(str(type_symbol["id"]))
                table_location = locations.get(str(table_symbol["id"]))
                if type_location is None or table_location is None:
                    errors.append(
                        f"ARC3404 DATABASE_LOCATION_MISSING: no schema file for {entity_key}."
                    )
                    continue
                type_path = str(type_location["path"])
                table_path = str(table_location["path"])
                if type_path != table_path:
                    errors.append(
                        f"ARC3405 DATABASE_LOCATION_CONFLICT: entity symbols for {entity_key} "
                        "must share one file."
                    )
                    continue
                source, lowered_checks, import_plan = _render_database_entity_file(
                    entity,
                    database_schema.get("constraints", []),
                    type_symbol,
                    table_symbol,
                    entities,
                    entity_symbols,
                    locations,
                    errors,
                    warnings,
                )
                sources[type_path] = source
                tables.append(
                    {
                        "entity": entity_key,
                        "table": entity_key,
                        "table_symbol": str(table_symbol["symbol"]),
                        "record_symbol": str(type_symbol["symbol"]),
                        "path": type_path,
                        "lowered_checks": lowered_checks,
                        "imports": import_plan,
                    }
                )

            schema_paths = sorted({item["path"] for item in tables})
            sources["backend/src/db/schema/index.ts"] = _render_barrel(
                "backend/src/db/schema/index.ts",
                schema_paths,
            )

        manifest = {
            "schema_version": DATABASE_MANIFEST_SCHEMA_VERSION,
            "status": DATABASE_SCHEMA_LOWERED if not errors else "DATABASE_SCHEMA_LOWERING_FAILED",
            "dialect": "sqlite",
            "orm": "drizzle",
            "tables": tables,
            "application_constraints": application_constraints,
            "planned_files": sorted(sources),
            "generated_files": [] if errors else sorted(sources),
        }
        return DatabaseSchemaLoweringResult(
            manifest=manifest,
            sources={} if errors else sources,
            errors=list(dict.fromkeys(errors)),
            warnings=list(dict.fromkeys(warnings)),
        )


def _index_symbols(
    registry: Any,
    errors: list[str],
    code: str,
) -> dict[str, dict[str, Any]]:
    rows = registry.get("symbols", []) if isinstance(registry, dict) else []
    if not isinstance(rows, list):
        errors.append(f"{code} SYMBOL_REGISTRY_INVALID: symbols must be a list.")
        return {}
    result: dict[str, dict[str, Any]] = {}
    for row in rows:
        symbol_id = str(row.get("id", "")).strip() if isinstance(row, dict) else ""
        if not symbol_id or symbol_id in result:
            errors.append(f"{code} SYMBOL_REGISTRY_INVALID: invalid or duplicate symbol {symbol_id!r}.")
            continue
        result[symbol_id] = row
    return result


def _index_symbol_locations(
    registry: Any,
    errors: list[str],
    code: str,
) -> dict[str, dict[str, Any]]:
    rows = registry.get("symbol_locations", []) if isinstance(registry, dict) else []
    if not isinstance(rows, list):
        errors.append(f"{code} FILE_REGISTRY_INVALID: symbol_locations must be a list.")
        return {}
    result: dict[str, dict[str, Any]] = {}
    for row in rows:
        symbol_id = str(row.get("symbol_id", "")).strip() if isinstance(row, dict) else ""
        path = str(row.get("path", "")).strip() if isinstance(row, dict) else ""
        if not symbol_id or not path or symbol_id in result:
            errors.append(f"{code} FILE_REGISTRY_INVALID: invalid location for {symbol_id!r}.")
            continue
        result[symbol_id] = row
    return result


def _validate_registry_statuses(
    symbol_registry: Any,
    file_registry: Any,
    errors: list[str],
    code: str,
) -> None:
    if not isinstance(symbol_registry, dict) or symbol_registry.get("status") != "SYMBOLS_PLANNED":
        errors.append(f"{code} SYMBOL_REGISTRY_INVALID: symbols are not planned.")
    if not isinstance(file_registry, dict) or file_registry.get("status") != "FILES_PLANNED":
        errors.append(f"{code} FILE_REGISTRY_INVALID: files are not planned.")


def _validate_required_files(
    registry: Any,
    required: set[str],
    errors: list[str],
    code: str,
) -> None:
    rows = registry.get("files", []) if isinstance(registry, dict) else []
    if not isinstance(rows, list):
        errors.append(f"{code} FILE_REGISTRY_INVALID: files must be a list.")
        return
    paths = {
        str(row.get("path", ""))
        for row in rows
        if isinstance(row, dict) and row.get("path")
    }
    if required - paths:
        errors.append(
            f"{code} FILE_REGISTRY_INVALID: required files are missing: {sorted(required - paths)}."
        )


def _definition_rows(
    symbols: list[dict[str, Any]],
    path: str,
    kind: str,
) -> list[dict[str, Any]]:
    return [
        {
            "symbol_id": str(symbol["id"]),
            "symbol": str(symbol["symbol"]),
            "kind": kind,
            "path": path,
        }
        for symbol in symbols
    ]


def _render_runtime_types() -> str:
    return (
        "// Generated by ARC. Do not edit.\n"
        "export type JsonPrimitive = string | number | boolean | null;\n"
        "export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };\n"
    )


def _render_contract_file(symbols: list[dict[str, Any]], errors: list[str]) -> str:
    uses_json = any(
        str(field_item.get("type", "")) == "json"
        for symbol in symbols
        for field_item in symbol.get("fields", [])
        if isinstance(field_item, dict)
    )
    lines = ["// Generated by ARC. Do not edit."]
    if uses_json:
        lines.extend(['import type { JsonValue } from "./runtime.js";', ""])
    for symbol in sorted(symbols, key=lambda item: str(item.get("id", ""))):
        name = str(symbol.get("symbol", ""))
        fields = symbol.get("fields", [])
        if not name or not isinstance(fields, list):
            errors.append(f"ARC3306 DATA_CONTRACT_INVALID: malformed contract {symbol.get('id')}.")
            continue
        lines.append(f"export interface {name} {{")
        for field_item in fields:
            if not isinstance(field_item, dict):
                errors.append(
                    f"ARC3306 DATA_CONTRACT_INVALID: malformed field in {symbol.get('id')}."
                )
                continue
            field_name = str(field_item.get("name", ""))
            type_name = _typescript_type(field_item.get("type"), DESIGN_TYPE_MAP, errors, "ARC3307")
            optional = "" if bool(field_item.get("required", True)) else "?"
            if not _is_typescript_property(field_name):
                errors.append(
                    f"ARC3306 DATA_CONTRACT_INVALID: invalid field name {field_name!r} in {symbol.get('id')}."
                )
                continue
            lines.append(f"  {field_name}{optional}: {type_name};")
        lines.extend(["}", ""])
    return "\n".join(lines).rstrip() + "\n"


def _render_entity_type_file(symbol: dict[str, Any], errors: list[str]) -> str:
    uses_json = any(
        isinstance(field_item, dict) and field_item.get("type") == "json"
        for field_item in symbol.get("fields", [])
    )
    lines = ["// Generated by ARC. Do not edit."]
    if uses_json:
        lines.extend(['import type { JsonValue } from "@arc/shared";', ""])
    lines.extend(_render_entity_interface(symbol, errors))
    return "\n".join(lines).rstrip() + "\n"


def _render_entity_interface(symbol: dict[str, Any], errors: list[str]) -> list[str]:
    name = str(symbol.get("symbol", ""))
    fields = symbol.get("fields", [])
    if not name or not isinstance(fields, list):
        errors.append(f"ARC3308 ENTITY_TYPE_INVALID: malformed entity {symbol.get('id')}.")
        return []
    lines = [f"export interface {name} {{"]
    for field_item in fields:
        if not isinstance(field_item, dict):
            errors.append(f"ARC3308 ENTITY_TYPE_INVALID: malformed field in {symbol.get('id')}.")
            continue
        field_name = str(field_item.get("name", ""))
        if not _is_typescript_property(field_name):
            errors.append(
                f"ARC3308 ENTITY_TYPE_INVALID: invalid field name {field_name!r} in {symbol.get('id')}."
            )
            continue
        type_name = _database_field_typescript_type(field_item, errors)
        nullable = " | null" if bool(field_item.get("nullable")) else ""
        lines.append(f"  {field_name}: {type_name}{nullable};")
    lines.extend(["}", ""])
    return lines


def _database_field_typescript_type(field_item: dict[str, Any], errors: list[str]) -> str:
    enum_values = field_item.get("properties", {}).get("enum")
    if isinstance(enum_values, list) and enum_values:
        return " | ".join(json.dumps(str(value), ensure_ascii=False) for value in enum_values)
    return _typescript_type(field_item.get("type"), DATABASE_TYPE_MAP, errors, "ARC3309")


def _typescript_type(
    value: Any,
    mapping: dict[str, str],
    errors: list[str],
    code: str,
) -> str:
    key = str(value)
    result = mapping.get(key)
    if result is None:
        errors.append(f"{code} TYPE_UNSUPPORTED: cannot lower type {key!r}.")
        return "never"
    return result


def _render_barrel(barrel_path: str, source_paths: list[str]) -> str:
    lines = ["// Generated by ARC. Do not edit."]
    for source_path in sorted(set(source_paths)):
        if source_path == barrel_path:
            continue
        specifier = posixpath.relpath(source_path, posixpath.dirname(barrel_path))
        if not specifier.startswith("."):
            specifier = f"./{specifier}"
        specifier = re.sub(r"\.ts$", ".js", specifier)
        lines.append(f'export * from "{specifier}";')
    return "\n".join(lines) + "\n"


def _index_entities(schema: Any, errors: list[str]) -> dict[str, dict[str, Any]]:
    rows = schema.get("entities", []) if isinstance(schema, dict) else []
    if not isinstance(rows, list):
        errors.append("ARC3406 DATABASE_SCHEMA_INVALID: entities must be a list.")
        return {}
    result: dict[str, dict[str, Any]] = {}
    for row in rows:
        key = str(row.get("key", "")).strip() if isinstance(row, dict) else ""
        if not key or key in result:
            errors.append(f"ARC3406 DATABASE_SCHEMA_INVALID: invalid or duplicate entity {key!r}.")
            continue
        result[key] = row
    return result


def _index_entity_symbols(
    symbols: dict[str, dict[str, Any]],
    errors: list[str],
) -> dict[str, tuple[dict[str, Any], dict[str, Any]]]:
    grouped: dict[str, dict[str, dict[str, Any]]] = {}
    for symbol in symbols.values():
        kind = str(symbol.get("kind", ""))
        if kind not in {"ENTITY_TYPE", "ENTITY_TABLE"}:
            continue
        entity = str(symbol.get("entity", "")).strip()
        if not entity or kind in grouped.setdefault(entity, {}):
            errors.append(f"ARC3407 ENTITY_SYMBOL_INVALID: invalid {kind} symbol for {entity!r}.")
            continue
        grouped[entity][kind] = symbol
    result: dict[str, tuple[dict[str, Any], dict[str, Any]]] = {}
    for entity, kinds in sorted(grouped.items()):
        if set(kinds) != {"ENTITY_TYPE", "ENTITY_TABLE"}:
            errors.append(f"ARC3407 ENTITY_SYMBOL_INVALID: incomplete entity symbols for {entity}.")
            continue
        result[entity] = (kinds["ENTITY_TYPE"], kinds["ENTITY_TABLE"])
    return result


def _validate_database_status(schema: Any, errors: list[str]) -> None:
    if not isinstance(schema, dict) or schema.get("status") != "RESOLVED":
        errors.append("ARC3406 DATABASE_SCHEMA_INVALID: schema status must be RESOLVED.")


def _validate_entity_coverage(
    entities: dict[str, dict[str, Any]],
    symbols: dict[str, tuple[dict[str, Any], dict[str, Any]]],
    errors: list[str],
) -> None:
    if set(entities) != set(symbols):
        errors.append(
            "ARC3407 ENTITY_SYMBOL_INVALID: entity and symbol sets differ: "
            f"missing_symbols={sorted(set(entities) - set(symbols))}, "
            f"unknown_symbols={sorted(set(symbols) - set(entities))}."
        )


def _application_constraints(schema: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        copy.deepcopy(constraint)
        for constraint in schema.get("constraints", [])
        if isinstance(constraint, dict) and constraint.get("enforcement") == "APPLICATION"
    ]


def _render_database_entity_file(
    entity: dict[str, Any],
    constraints: list[dict[str, Any]],
    type_symbol: dict[str, Any],
    table_symbol: dict[str, Any],
    entities: dict[str, dict[str, Any]],
    entity_symbols: dict[str, tuple[dict[str, Any], dict[str, Any]]],
    locations: dict[str, dict[str, Any]],
    errors: list[str],
    warnings: list[str],
) -> tuple[str, list[str], list[dict[str, Any]]]:
    entity_key = str(entity["key"])
    current_path = str(locations[str(table_symbol["id"])]["path"])
    fields = entity.get("fields", [])
    if not isinstance(fields, list):
        errors.append(f"ARC3406 DATABASE_SCHEMA_INVALID: fields must be a list for {entity_key}.")
        return "", [], []

    uses_json = any(isinstance(item, dict) and item.get("type") == "json" for item in fields)
    imports: dict[str, set[str]] = {"drizzle-orm/sqlite-core": {"sqliteTable"}}
    import_sources: dict[tuple[str, str], str] = {}
    if uses_json:
        imports.setdefault("@arc/shared", set()).add("JsonValue")
        import_sources[("@arc/shared", "JsonValue")] = "shared/src/index.ts"

    referenced_tables: dict[str, tuple[str, str]] = {}
    builders: list[tuple[dict[str, Any], str]] = []
    for field_item in fields:
        if not isinstance(field_item, dict):
            errors.append(f"ARC3406 DATABASE_SCHEMA_INVALID: malformed field in {entity_key}.")
            continue
        builder, drizzle_import = _drizzle_column_builder(field_item, errors)
        imports["drizzle-orm/sqlite-core"].add(drizzle_import)
        reference = field_item.get("references")
        if reference:
            target_entity, separator, target_field = str(reference).partition(".")
            if not separator or target_entity not in entities or target_entity not in entity_symbols:
                errors.append(
                    f"ARC3409 FOREIGN_KEY_INVALID: {entity_key}.{field_item.get('name')} "
                    f"references unknown field {reference!r}."
                )
            else:
                target_table_symbol = entity_symbols[target_entity][1]
                target_location = locations.get(str(target_table_symbol["id"]))
                if target_location is None:
                    errors.append(
                        f"ARC3404 DATABASE_LOCATION_MISSING: no table file for {target_entity}."
                    )
                    continue
                target_path = str(target_location["path"])
                if target_entity != entity_key:
                    specifier = _relative_module_specifier(current_path, target_path)
                    target_symbol = str(target_table_symbol["symbol"])
                    imports.setdefault(specifier, set()).add(target_symbol)
                    import_sources[(specifier, target_symbol)] = target_path
                referenced_tables[str(field_item.get("name"))] = (
                    str(target_table_symbol["symbol"]),
                    target_field,
                )
        builders.append((field_item, builder))

    single_unique, composite_unique = _unique_constraints(entity_key, constraints)
    checks = _field_checks(entity, errors, warnings)
    if composite_unique:
        imports["drizzle-orm/sqlite-core"].add("uniqueIndex")
    if referenced_tables:
        imports["drizzle-orm/sqlite-core"].add("AnySQLiteColumn")
    if checks:
        imports["drizzle-orm/sqlite-core"].add("check")
        imports.setdefault("drizzle-orm", set()).add("sql")

    lines = ["// Generated by ARC. Do not edit."]
    for module_name in sorted(imports):
        names = ", ".join(
            f"type {name}" if name == "AnySQLiteColumn" else name
            for name in sorted(imports[module_name])
        )
        type_prefix = "type " if module_name == "@arc/shared" else ""
        lines.append(f'import {type_prefix}{{ {names} }} from "{module_name}";')
    lines.append("")
    lines.extend(_render_entity_interface(type_symbol, errors))

    table_name = entity_key
    table_variable = str(table_symbol["symbol"])
    lines.append(f'export const {table_variable} = sqliteTable("{_escape_string(table_name)}", {{')
    for field_item, builder in builders:
        field_name = str(field_item.get("name", ""))
        chain = builder
        if bool(field_item.get("primary_key")):
            chain += ".primaryKey()"
        if not bool(field_item.get("nullable")) and not bool(field_item.get("primary_key")):
            chain += ".notNull()"
        if field_name in single_unique and not bool(field_item.get("primary_key")):
            chain += ".unique()"
        if field_name in referenced_tables:
            target_table, target_field = referenced_tables[field_name]
            chain += f".references((): AnySQLiteColumn => {target_table}.{target_field})"
        default = field_item.get("properties", {}).get("default")
        if default is not None:
            chain += f".default({_typescript_literal(default)})"
        lines.append(f"  {field_name}: {chain},")
    extra_entries: list[str] = []
    for fields_in_index in composite_unique:
        suffix = "_".join(fields_in_index)
        columns = ", ".join(f"table.{name}" for name in fields_in_index)
        extra_entries.append(
            f'  uniqueIndex("{_escape_string(entity_key)}_{_escape_string(suffix)}_unique").on({columns}),'
        )
    lowered_checks: list[str] = []
    for field_name, kind, expression in checks:
        check_name = f"{entity_key}_{field_name}_{kind}_check"
        extra_entries.append(f'  check("{_escape_string(check_name)}", sql`{expression}`),')
        lowered_checks.append(check_name)
    if extra_entries:
        lines.append("}, (table) => [")
        lines.extend(extra_entries)
        lines.append("]);")
    else:
        lines.append("});")
    lines.append("")
    import_plan = []
    for module_name in sorted(imports):
        for name in sorted(imports[module_name]):
            row = {
                "symbol": name,
                "specifier": module_name,
                "import_style": "named",
                "type_only": module_name == "@arc/shared" or name == "AnySQLiteColumn",
            }
            source = import_sources.get((module_name, name))
            if source is not None:
                row["from"] = source
            import_plan.append(row)
    return "\n".join(lines), lowered_checks, import_plan


def _drizzle_column_builder(field_item: dict[str, Any], errors: list[str]) -> tuple[str, str]:
    name = str(field_item.get("name", ""))
    escaped = _escape_string(name)
    field_type = str(field_item.get("type", ""))
    if field_type in {"string", "uuid", "date", "datetime", "foreign_key"}:
        return f'text("{escaped}")', "text"
    if field_type == "json":
        return f'text("{escaped}", {{ mode: "json" }}).$type<JsonValue>()', "text"
    if field_type == "integer":
        return f'integer("{escaped}")', "integer"
    if field_type == "boolean":
        return f'integer("{escaped}", {{ mode: "boolean" }})', "integer"
    if field_type == "number":
        return f'real("{escaped}")', "real"
    errors.append(f"ARC3410 DATABASE_TYPE_UNSUPPORTED: cannot lower {field_type!r} for {name}.")
    return f'text("{escaped}")', "text"


def _unique_constraints(
    entity_key: str,
    constraints: list[dict[str, Any]],
) -> tuple[set[str], list[list[str]]]:
    single: set[str] = set()
    composite: set[tuple[str, ...]] = set()
    for constraint in constraints:
        if (
            not isinstance(constraint, dict)
            or constraint.get("type") not in {"UNIQUE", "COMPOSITE_UNIQUE"}
            or constraint.get("enforcement") != "DATABASE"
        ):
            continue
        references = [str(value) for value in constraint.get("fields", [])]
        if not references or any(
            reference.partition(".")[0] != entity_key for reference in references
        ):
            continue
        names = tuple(reference.partition(".")[2] for reference in references)
        if len(names) == 1:
            single.add(names[0])
        elif len(names) > 1:
            composite.add(names)
    return single, [list(value) for value in sorted(composite)]


def _field_checks(
    entity: dict[str, Any],
    errors: list[str],
    warnings: list[str],
) -> list[tuple[str, str, str]]:
    result: list[tuple[str, str, str]] = []
    for field_item in entity.get("fields", []):
        if not isinstance(field_item, dict):
            continue
        name = str(field_item.get("name", ""))
        properties = field_item.get("properties", {})
        if not isinstance(properties, dict):
            errors.append(f"ARC3406 DATABASE_SCHEMA_INVALID: properties must be an object for {name}.")
            continue
        for kind, value in sorted(properties.items()):
            if value is None or value is False or kind in {"default", "format"}:
                continue
            if value == "" or value == []:
                warnings.append(
                    f"ARC3412 DATABASE_CHECK_UNSUPPORTED: empty {kind} for {name}; skipped."
                )
                continue
            expression = _property_check_expression(name, kind, value, warnings)
            if expression is not None:
                result.append((name, kind, expression))
    return result


def _property_check_expression(
    field_name: str,
    kind: str,
    value: Any,
    warnings: list[str],
) -> str | None:
    field = f"${{table.{field_name}}}"
    if kind == "min_length":
        try:
            number = int(value)
        except (TypeError, ValueError):
            warnings.append(
                f"ARC3412 DATABASE_CHECK_UNSUPPORTED: invalid min_length for {field_name}; skipped."
            )
            return None
        if number < 0:
            warnings.append(
                f"ARC3412 DATABASE_CHECK_UNSUPPORTED: negative min_length for {field_name}; skipped."
            )
            return None
        return f"length({field}) >= {number}"
    if kind == "max_length":
        try:
            number = int(value)
        except (TypeError, ValueError):
            warnings.append(
                f"ARC3412 DATABASE_CHECK_UNSUPPORTED: invalid max_length for {field_name}; skipped."
            )
            return None
        if number < 0:
            warnings.append(
                f"ARC3412 DATABASE_CHECK_UNSUPPORTED: negative max_length for {field_name}; skipped."
            )
            return None
        return f"length({field}) <= {number}"
    if kind == "minimum":
        return f"{field} >= {_sql_literal(value)}"
    if kind == "maximum":
        return f"{field} <= {_sql_literal(value)}"
    if kind == "enum":
        if not isinstance(value, list) or not value:
            warnings.append(
                f"ARC3412 DATABASE_CHECK_UNSUPPORTED: invalid enum for {field_name}; skipped."
            )
            return None
        values = ", ".join(_sql_literal(item) for item in value)
        return f"{field} in ({values})"
    if kind == "date_past" and value is True:
        return f"{field} < datetime('now')"
    if kind == "date_future" and value is True:
        return f"{field} > datetime('now')"
    if kind == "pattern":
        if not str(value):
            return None
        warnings.append(
            "ARC3411 DATABASE_PATTERN_UNSUPPORTED: SQLite cannot enforce regex pattern "
            f"for {field_name}; skipped."
        )
        return None
    warnings.append(
        f"ARC3412 DATABASE_CHECK_UNSUPPORTED: cannot lower {kind} for {field_name}; skipped."
    )
    return None


def _relative_module_specifier(current_path: str, target_path: str) -> str:
    relative = posixpath.relpath(target_path, posixpath.dirname(current_path))
    if not relative.startswith("."):
        relative = f"./{relative}"
    return re.sub(r"\.ts$", ".js", relative)


def _typescript_literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _sql_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    text = str(value).replace("'", "''").replace("`", "\\`").replace("${", "\\${")
    return "'" + text + "'"


def _escape_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _is_typescript_property(value: str) -> bool:
    return re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", value) is not None
